apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: tocomo
spec:
  environments:
    - name: dev
      build:
        from: main
    - name: test
      build:
        from: main
    - name: prod
  dnsAlias:
    - alias: tocomo
      component: frontend
      environment: prod
  components:
    - name: frontend
      ports:
        - name: http
          port: 3000
      publicPort: http
      src: frontend
    - name: backend
      src: backend
      ports:
        - name: http
          port: 5005
      publicPort: http
