apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: co2specdemo
spec:
  environments:
    - name: dev
      build:
        from: main
  dnsAlias:
    - alias: co2specdemo
      component: frontend
      environment: dev
  components:
    - name: frontend
      ports:
        - name: http
          port: 3000
      publicPort: http
      src: frontend
      authentication:
        oauth2:
          clientId: a4f4519a-fafb-48c2-9a5c-3ba38309a824
          scope: openid profile email offline_access
          setXAuthRequestHeaders: true
          setAuthorizationHeader: true
          sessionStoreType: redis
          redisStore:
            connectionUrl: redis://redis:6379
    - name: redis
      image: bitnami/redis:latest
      secrets:
        - REDIS_PASSWORD
      ports:
        - name: redis
          port: 6379
    - name: backend
      src: backend
      ports:
        - name: http
          port: 5005
      publicPort: http
      authentication:
        oauth2:
          clientId: a4f4519a-fafb-48c2-9a5c-3ba38309a824
          scope: openid profile email offline_access
          setXAuthRequestHeaders: true
          setAuthorizationHeader: true
          sessionStoreType: redis
          redisStore:
            connectionUrl: redis://redis:6379
