name: test_backend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  python-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv
        run: nix profile install nixpkgs#devenv

      - name: Run tests
        run: devenv test
