name: test_backend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  python-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31.11.1
      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
      - name: Setup Nix development environment
        run: nix develop --impure --accept-flake-config --command true
      - name: Run tests
        shell: bash -c "nix develop --impure -c bash -- {0}"
        run: devenv test
