name: test_backend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  python-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Set up environment"
        run: docker compose -f docker-compose.yml up -d --wait
